server:
  port: 8081
spring:
  datasource:
    username: root
    password: Zhang!@#125799
    url: jdbc:mysql://120.25.242.229:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.qianqiangongzi.entity
logging:
  level:
    com:
      qianqiangongzi:
        dto: debug